### ISSUE TITLE
s_server ????

### ISSUE THREAD

**Issue by fdrouhin-uha** [iPresing/R309-SAE302#1]
J'ai eu un souci concernant la génération de s_server.exe
L'install de install_server.py doit être fait le même environnement ? Comment dois-je connaitre les paramètres AES_KEY ?

**Comment by fdrouhin-uha** [comment]
et python server.py crash car les variables d'env n'existe pas !

**Comment by fdrouhin-uha** [comment]
J'ai pris les paramètres par défaut mais si je lance s_server, j'ai un crash sur getenv(AES_KEY) ...

**Comment by fdrouhin-uha** [comment]
mise en place des variables d'environnement ...
set AES_KEY, set AES_IV pour les valeurs par défaut
Hop nouvelle erreur sur Incorrect ASE key length ...

**Comment by fdrouhin-uha** [comment]
Essai de nouveau avec des valeurs pour AES_KEY et AES_IV toujours le même problème

**Comment by fdrouhin-uha** [comment]
![Capture d'écran 2024-01-15 195535](https://github.com/iPresing/R309-SAE302/assets/119610743/64a4dee7-d4a1-4167-8890-7215baad402b)

**Comment by fdrouhin-uha** [comment]
![Capture d'écran 2024-01-15 195810](https://github.com/iPresing/R309-SAE302/assets/119610743/0b239b33-48eb-41ab-9b3e-30f7283b8b0a)

**Comment by fdrouhin-uha** [comment]
Je ne sais plus avancer ...

**Comment by iPresing** [comment]
Bonsoir Monsieur, comme indiqué via mail, afin que le script d'installation fonctionne **il aurait fallu spécifier une clé de taille 32 caractères et un IV de taille de 16 caractères**. Si vous avez d'autres questions n'hésitez pas.

Bonne soirée
